const actions = {
  SET_FILM_QUERY_DATA: "films/SET_FILM_QUERY_DATA",
  SET_FILM_DATA: "films/SET_FILM_DATA",
  LOAD_FILMS_REQUEST: "films/LOAD_FILMS_REQUEST",
  LOAD_FILMS_SUCCESS: "films/LOAD_FILMS_SUCCESS",
  LOAD_FILMS_FAILURE: "films/LOAD_FILMS_FAILURE",

  GET_FILM_REQUEST: "films/GET_FILM_REQUEST",
  GET_FILM_SUCCESS: "films/GET_FILM_SUCCESS",
  GET_FILM_FAILURE: "films/GET_FILM_FAILURE",

  UPDATE_FILM_RATING_REQUEST: "films/UPDATE_FILM_RATING_REQUEST",
  UPDATE_FILM_RATING_SUCCESS: "films/UPDATE_FILM_RATING_SUCCESS",
  UPDATE_FILM_RATING_FAILURE: "films/UPDATE_FILM_RATING_FAILURE",

  CREATE_FILM_RATING_REQUEST: "films/CREATE_FILM_RATING_REQUEST",
  CREATE_FILM_RATING_SUCCESS: "films/CREATE_FILM_RATING_SUCCESS",
  CREATE_FILM_RATING_FAILURE: "films/CREATE_FILM_RATING_FAILURE",

  SET_USER_FILM: "films/SET_USER_FILM",
};

export default actions;
